# Generated by Django 1.9.5 on 2016-05-02 05:38
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("emails", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="emailsubscription",
            name="subscription",
            field=models.CharField(
                choices=[("ALL", "General"), ("NEWS", "Newsletter")],
                default="ALL",
                max_length=6,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailsubscription", unique_together={("user", "subscription")}
        ),
    ]
