# Generated by Django 1.9.4 on 2016-03-13 08:06
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="The amount of money the artist wishes to raise"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="The reason why the artist is raising money, in a few words",
                        max_length=40,
                    ),
                ),
                (
                    "value_per_share",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The value (in dollars) per share the artist wishes to sell",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the campaign will start accepting investors",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the campaign ends and will no longer accept investors (no end date if blank)",
                        null=True,
                    ),
                ),
                (
                    "use_of_funds",
                    models.TextField(
                        blank=True,
                        help_text="A description of how the funds will be used",
                        null=True,
                    ),
                ),
                (
                    "fans_percentage",
                    models.PositiveSmallIntegerField(
                        help_text="The percentage of revenue that goes back to the fans (a value from 0-100)"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="artist.Artist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense",
                    models.CharField(
                        help_text="A description of one of the expenses for the artist (eg. Studio cost)",
                        max_length=30,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.Campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_datetime",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "num_shares",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The number of shares a user made in a transaction",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.Campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RevenueReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="The amount of revenue generated (in dollars) being reported (since last report)"
                    ),
                ),
                ("reported_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.Campaign",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="expense", unique_together={("campaign", "expense")}
        ),
    ]
