# Generated by Django 1.9.6 on 2016-05-06 06:55
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    def create_initial_userprofiles(apps, schema_editor):
        User = apps.get_model(settings.AUTH_USER_MODEL)
        UserProfile = apps.get_model("accounts", "UserProfile")
        for user in User.objects.all():
            UserProfile.objects.create(user=user)

    operations = [
        migrations.RunPython(create_initial_userprofiles, migrations.RunPython.noop)
    ]
