# Generated by Django 1.9.7 on 2016-06-23 06:57
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_auto_20160522_2139")]

    def usernames_to_lowercase(apps, schema_editor):
        User = apps.get_model(settings.AUTH_USER_MODEL)
        for user in User.objects.all():
            user.username = user.username.lower()
            user.save()

    operations = [
        migrations.RunPython(usernames_to_lowercase, migrations.RunPython.noop)
    ]
