# Generated by Django 1.10.7 on 2017-05-28 22:50
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0006_auto_20161115_0635")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.UserAvatar",
            ),
        )
    ]
