# Generated by Django 1.9.6 on 2016-05-22 21:39
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("artist", "0002_auto_20160317_0521")]

    operations = [
        migrations.AlterField(
            model_name="bio",
            name="bio",
            field=models.TextField(
                help_text='Short biography of artist. <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> allowed, but no raw HTML. Examples: **bold**, *italic*, indent 4 spaces for a code block.'
            ),
        )
    ]
