# Generated by Django 1.10.5 on 2017-02-01 07:54
from django.db import migrations

from artist.models import Playlist as PlaylistConst


class Migration(migrations.Migration):

    dependencies = [("artist", "0009_auto_20170201_0753")]

    def copy_soundcloud_playlists_to_playlist(apps, schema_editor):
        SoundCloudPlaylist = apps.get_model("artist", "SoundCloudPlaylist")
        Playlist = apps.get_model("artist", "Playlist")

        for scplaylist in SoundCloudPlaylist.objects.all():
            Playlist.objects.get_or_create(
                artist=scplaylist.artist,
                provider=PlaylistConst.PLAYLIST_PROVIDER_SOUNDCLOUD,
                uri=scplaylist.playlist,
            )

    # Note: Running the reverse migration on a database that contains playlists
    # from providers other than SoundCloud will result in data loss
    def copy_playlists_to_soundcloud_playlist(apps, schema_editor):
        SoundCloudPlaylist = apps.get_model("artist", "SoundCloudPlaylist")
        Playlist = apps.get_model("artist", "Playlist")

        for playlist in Playlist.objects.filter(
            provider=PlaylistConst.PLAYLIST_PROVIDER_SOUNDCLOUD
        ):
            SoundCloudPlaylist.objects.get_or_create(
                artist=playlist.artist, playlist=playlist.uri
            )

    operations = [
        migrations.RunPython(
            copy_soundcloud_playlists_to_playlist, copy_playlists_to_soundcloud_playlist
        )
    ]
