# Generated by Django 1.10.5 on 2017-02-01 08:20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("artist", "0011_auto_20170201_0754")]

    operations = [
        migrations.AlterField(
            model_name="updatemediaurl",
            name="media_type",
            field=models.CharField(choices=[("youtube", "YouTube")], max_length=8),
        )
    ]
